name: .NET MAUI CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build-android:
    runs-on: windows-latest  # Android build on Windows
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI Workload
        run: dotnet workload install maui

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Android
        run: dotnet build -f net8.0-android --no-restore --configuration Release --warnaserror

      - name: Run Tests
        run: dotnet test --no-restore --verbosity normal
