name: .NET MAUI CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build-android:
    runs-on: windows-latest  # Android build on Windows
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI Workload
        run: dotnet workload install maui

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Android
        run: dotnet build -f net8.0-android --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test --no-restore --verbosity normal

  build-ios:
    runs-on: macos-latest  # iOS build on macOS
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI Workload
        run: dotnet workload install maui

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build iOS
        run: dotnet build -f net8.0-ios --no-restore --configuration Release
        if: runner.os == 'macOS'

      - name: Run Tests
        run: dotnet test --no-restore --verbosity normal

  deploy:
    needs: [build-android, build-ios]  # Ensure deploy happens after both builds
    runs-on: macos-latest  # You can also use windows-latest here, depending on where you deploy from
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Server (Replace with actual deploy command)
        run: echo "Deploying the app..."
