name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Get next version
      id: get_next_version
      uses: thenativeweb/get-next-version@main
      with:
        prefix: 'v'

    - name: Debug Version Output
      run: |
        echo "Has Next Version: ${{ steps.get_next_version.outputs.hasNextVersion }}"
        echo "Next Version: ${{ steps.get_next_version.outputs.version }}"

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Create release
      if: steps.get_next_version.outputs.hasNextVersion == 'true'
      run: |
        NEXT_VERSION=${{ steps.get_next_version.outputs.version }}
        echo "Tagging version $NEXT_VERSION"
        git tag $NEXT_VERSION
        git push origin $NEXT_VERSION
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug Git Tagging
      run: |
        git tag
        git log --oneline -5